use std::io::Result;

fn main() -> Result<()> {
    prost_build::Config::new()
        .default_package_filename("proto")
        .compile_protos(
            &[
                "streamlit/proto/ForwardMsg.proto",
                "streamlit/proto/BackMsg.proto",
                "streamlit/proto/Element.proto",
                "streamlit/proto/Text.proto",
                "streamlit/proto/Heading.proto",
                "streamlit/proto/Code.proto",
                "streamlit/proto/Markdown.proto",
                "streamlit/proto/Empty.proto",
                "streamlit/proto/Button.proto",
                "streamlit/proto/HeightConfig.proto",
                "streamlit/proto/WidthConfig.proto",
                "streamlit/proto/TextAlignmentConfig.proto",
                "streamlit/proto/ButtonLikeIconPosition.proto",
                "streamlit/proto/Alert.proto",
                "streamlit/proto/Image.proto",
                "streamlit/proto/Balloons.proto",
                "streamlit/proto/Snow.proto",
                "streamlit/proto/Block.proto",
                "streamlit/proto/Slider.proto",
                "streamlit/proto/Checkbox.proto",
                "streamlit/proto/TextInput.proto",
                "streamlit/proto/TextArea.proto",
                "streamlit/proto/Selectbox.proto",
                "streamlit/proto/Radio.proto",
                "streamlit/proto/NumberInput.proto",
                "streamlit/proto/Metric.proto",
                "streamlit/proto/Progress.proto",
                "streamlit/proto/Spinner.proto",
                "streamlit/proto/DataFrame.proto",
                "streamlit/proto/Arrow.proto",
                "streamlit/proto/NamedDataSet.proto",
                "streamlit/proto/FileUploader.proto",
                "streamlit/proto/DownloadButton.proto",
                "streamlit/proto/PlotlyChart.proto",
                "streamlit/proto/ColorPicker.proto",
                "streamlit/proto/TimeInput.proto",
                "streamlit/proto/DateInput.proto",
                "streamlit/proto/MultiSelect.proto",
            ],
            &[".."],
        )?;
    Ok(())
}
